import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath, URL } from "node:url";
import { test } from "node:test";

const script = fileURLToPath(new URL("./e2e-apk.mjs", import.meta.url));
const commit = "a".repeat(40);
function fixture(t) {
  const directory = mkdtempSync(join(tmpdir(), "mobile-apk-"));
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  writeFileSync(join(directory, "app-release.apk"), "synthetic APK bytes");
  return directory;
}
function run(mode, directory, sha = commit) {
  return spawnSync(process.execPath, [script, mode, directory, sha], {
    encoding: "utf8",
  });
}
function seal(directory) {
  assert.equal(run("seal", directory).status, 0);
}

test("same checkout and unchanged artifact verify across job handoff", (t) => {
  const directory = fixture(t);
  seal(directory);
  assert.equal(run("verify", directory).status, 0);
});
test("different checkout fails closed", (t) => {
  const directory = fixture(t);
  seal(directory);
  assert.notEqual(run("verify", directory, "b".repeat(40)).status, 0);
});
test("same-size artifact corruption fails closed", (t) => {
  const directory = fixture(t);
  seal(directory);
  writeFileSync(join(directory, "app-release.apk"), "synthetic APK byte!");
  assert.notEqual(run("verify", directory).status, 0);
});
test("missing manifest cannot be silently regenerated by verification", (t) => {
  assert.notEqual(run("verify", fixture(t)).status, 0);
});
test("missing or empty APK is rejected", (t) => {
  const directory = fixture(t);
  writeFileSync(join(directory, "app-release.apk"), "");
  assert.notEqual(run("seal", directory).status, 0);
  rmSync(join(directory, "app-release.apk"));
  assert.notEqual(run("seal", directory).status, 0);
});
test("short commit and accidental manifest overwrite are rejected", (t) => {
  const directory = fixture(t);
  assert.notEqual(run("seal", directory, "aaaaaaa").status, 0);
  seal(directory);
  assert.notEqual(run("seal", directory).status, 0);
});
for (const [field, value] of [
  ["architecture", "arm64-v8a"],
  ["file", "../other.apk"],
  ["schema", "unknown"],
]) {
  test(`changed manifest ${field} is rejected`, (t) => {
    const directory = fixture(t);
    seal(directory);
    const path = join(directory, "manifest.json");
    const manifest = JSON.parse(readFileSync(path, "utf8"));
    manifest[field] = value;
    writeFileSync(path, JSON.stringify(manifest));
    assert.notEqual(run("verify", directory).status, 0);
  });
}
