import assert from "node:assert/strict";
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath, URL } from "node:url";
import { test } from "node:test";

const script = fileURLToPath(new URL("./e2e-apk.mjs", import.meta.url));
const commit = "a".repeat(40);
function fixture(t, architectures = ["x86_64"]) {
  const directory = mkdtempSync(join(tmpdir(), "mobile-apk-"));
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  writeFileSync(join(directory, "AndroidManifest.xml"), "synthetic fixture");
  for (const architecture of architectures) {
    const lib = join(directory, "lib", architecture);
    mkdirSync(lib, { recursive: true });
    writeFileSync(join(lib, "libtest.so"), "synthetic library");
  }
  const zip = spawnSync(
    "zip",
    [
      "-q",
      "-r",
      "app-release.apk",
      "AndroidManifest.xml",
      ...(architectures.length ? ["lib"] : []),
    ],
    { cwd: directory },
  );
  assert.equal(zip.status, 0);
  return directory;
}
function run(mode, directory, sha = commit, architecture) {
  return spawnSync(
    process.execPath,
    [
      script,
      mode,
      directory,
      sha,
      ...(architecture === undefined ? [] : [architecture]),
    ],
    {
      encoding: "utf8",
    },
  );
}
function seal(directory) {
  assert.equal(run("seal", directory).status, 0);
}

test("same checkout and unchanged artifact verify across job handoff", (t) => {
  const directory = fixture(t);
  seal(directory);
  assert.equal(run("verify", directory).status, 0);
});
test("different checkout fails closed", (t) => {
  const directory = fixture(t);
  seal(directory);
  assert.notEqual(run("verify", directory, "b".repeat(40)).status, 0);
});
test("same-size artifact corruption fails closed", (t) => {
  const directory = fixture(t);
  seal(directory);
  const apk = readFileSync(join(directory, "app-release.apk"));
  apk[0] ^= 1;
  writeFileSync(join(directory, "app-release.apk"), apk);
  assert.notEqual(run("verify", directory).status, 0);
});
test("missing manifest cannot be silently regenerated by verification", (t) => {
  assert.notEqual(run("verify", fixture(t)).status, 0);
});
test("missing or empty APK is rejected", (t) => {
  const directory = fixture(t);
  writeFileSync(join(directory, "app-release.apk"), "");
  assert.notEqual(run("seal", directory).status, 0);
  rmSync(join(directory, "app-release.apk"));
  assert.notEqual(run("seal", directory).status, 0);
});
test("short commit and accidental manifest overwrite are rejected", (t) => {
  const directory = fixture(t);
  assert.notEqual(run("seal", directory, "aaaaaaa").status, 0);
  seal(directory);
  assert.notEqual(run("seal", directory).status, 0);
});
for (const [field, value] of [
  ["architecture", "arm64-v8a"],
  ["file", "../other.apk"],
  ["schema", "unknown"],
]) {
  test(`changed manifest ${field} is rejected`, (t) => {
    const directory = fixture(t);
    seal(directory);
    const path = join(directory, "manifest.json");
    const manifest = JSON.parse(readFileSync(path, "utf8"));
    manifest[field] = value;
    writeFileSync(path, JSON.stringify(manifest));
    assert.notEqual(run("verify", directory).status, 0);
  });
}

test("arm64 device artifact records and verifies its actual ABI", (t) => {
  const directory = fixture(t, ["arm64-v8a"]);
  assert.equal(run("seal", directory, commit, "arm64-v8a").status, 0);
  assert.equal(
    JSON.parse(readFileSync(join(directory, "manifest.json"))).architecture,
    "arm64-v8a",
  );
  assert.equal(run("verify", directory, commit, "arm64-v8a").status, 0);
  assert.notEqual(run("verify", directory).status, 0);
});
test("emulator artifact cannot satisfy a device target", (t) => {
  const directory = fixture(t);
  seal(directory);
  assert.notEqual(run("verify", directory, commit, "arm64-v8a").status, 0);
});
for (const abis of [[], ["arm64-v8a"], ["x86_64", "arm64-v8a"]]) {
  test(`emulator seal rejects missing or different ABI: ${abis}`, (t) => {
    assert.notEqual(run("seal", fixture(t, abis)).status, 0);
  });
}
test("unsupported architecture and non-ZIP bytes fail closed", (t) => {
  const directory = fixture(t);
  assert.notEqual(run("seal", directory, commit, "armv7").status, 0);
  writeFileSync(join(directory, "app-release.apk"), "not a ZIP");
  assert.notEqual(run("seal", directory).status, 0);
});
